#!/usr/bin/env bash
# Generate src/lib/buildInfo.ts with version info derived from build-manifest.json
# and build-system metadata.
# This script runs automatically before each build (dev & production).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/src/lib/buildInfo.ts"

# Read base version from build-manifest.json
BASE_VERSION=$(node "$ROOT/scripts/build-manifest.mjs" get appVersion)

# Build-system metadata
BUILD_NUMBER="${BUILD_NUMBER:-${GITHUB_RUN_NUMBER:-dev}}"
BUILD_HASH=$(git -C "$ROOT" rev-parse --short=7 HEAD 2>/dev/null || echo "unknown")
BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

cat > "$OUT" <<EOF
// Auto-generated by scripts/gen-build-info.sh — do not edit manually
export const APP_VERSION = "${BASE_VERSION}";
export const BUILD_NUMBER = "${BUILD_NUMBER}";
export const BUILD_HASH = "${BUILD_HASH}";
export const BUILD_TIME = "${BUILD_TIME}";
export const VERSION_DISPLAY = "v${BASE_VERSION} (build ${BUILD_NUMBER})";
EOF
